sudo: required

services:
  - docker

language: node_js

node_js:
  - "12.13.0"

before_install:
  - docker build -t beaubouchard/veneerbook .
script:
  - docker run beaubouchard/veneerbook npm run test
  - docker run -e "CODECOV_TOKEN=${CODECOV_TOKEN}" beaubouchard/veneerbook npm run cover
