version: "2"
services:
  veneerbook:
    container_name: veneerbook
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/srv/veneerbook
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
